### ISSUE TITLE
Wrong values in Example 5

### ISSUE THREAD

**Issue by jjant** [miladz68/coreum-challenge#1]
The values in the outputs for `account1` and `account2` should be negative (`-3`), because as they _sent_ their balances to `account_recipient`. Also the label says `Example 4` when it should be `5`.

https://github.com/miladz68/coreum-challenge/blob/c0d9b8ffa3147d943f1ed6bbb65729b028823bc0/README.md#L380-L394

**Comment by miladz68** [comment]
Thanks for your attention to detail. I made a PR to fix this.

**Comment by jjant** [comment]
Fixed in #2.
